# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e0b11c319c2ebf82a2e992325c66cf542f09149d4c329d1e8b866c957856578df3803332453e4f54908e12e75dcdbe375dd00796e4cd8bc85c0b8cd5d301b6c

test:
  secret_key_base: 6144381febb9c3c9cc43e3a87b1ba516621e9a78c2a2aa6f62349ab5a1e31397cc9baf5e5906968549aa081a782bbcf70f69ceaef87a9740727ef814fbbf1493

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
